export const languages: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  java: 'Java',
  kotlin: 'Kotlin',
  php: 'PHP',
  sql: 'SQL',
  css: 'CSS',
  sass: 'Sass',
  scss: 'SCSS',
  jsx: 'JSX',
  tsx: 'TSX',
  markup: 'HTML',
  bash: 'Bash',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  go: 'Go',
  ruby: 'Ruby',
  rust: 'Rust',
  swift: 'Swift',
  objectivec: 'Objective-C',
  json: 'JSON',
  yaml: 'YAML',
  docker: 'Dockerfile',
  powershell: 'PowerShell',
  perl: 'Perl',
  lua: 'Lua',
  r: 'R',
};

export const defaultLanguage = 'javascript';
