name: Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    if: contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
    uses: ./.github/workflows/common-prepare.yml

  build:
    needs: prepare
    if: >-
      contains(fromJSON('["niqzart", "unknownproperty"]'), github.triggering_actor)
      && needs.prepare.outputs.xi_front_files == 'true'

    uses: xi-effect/xi.actions/.github/workflows/docker-build.yml@main
    with:
      tag: front-main
    secrets: inherit
